#spring.application.name=project-board
debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fastcampus.projectboardadmin: debug
    org.springframework.web.servlet: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
    org.springframework.web.client.RestTemplate: debug

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/admin
    username: bomi #root #uno
    password: 1234 #1234 #thisisTestpw!#%&
    driverClassName: com.mysql.cj.jdbc.Driver
    #create user 'bomi'@'localhost' identified by '1234';
    #GRANT ALL PRIVILEGES ON admin.* TO 'bomi'@'localhost';
  jpa:
    defer-datasource-initialization: true
    hibernate.ddl-auto: create
    open-in-view: false
    show-sql: true
    properties:
      hibernate.format_sql: sql
      hibernate.hibernate.default_batch_fetch_size: 100
  sql.init.mode: always
  thymeleaf3:
    decoupled-logic: true
  devtools.livereload.port: 35730
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: ae2016a457af4af4a8451bb7d2f8d32b97f # ${KAKAO_OAUTH_CLIENT_ID}
            client-secret: KAKAO_OAUTH_CLIENT_SECRET # ${KAKAO_OAUTH_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            client-authentication-method: POST
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

server.port: 8081

project.board.url: http://localhost:8080

---

spring:
  config.activate.on-profile: test
  datasource.url: jdbc:h2:mem:testdb
